workspace:
  base: /workspace
  path: ikarus-frontend

pipeline:
  setup:npm:
    image: node:10-alpine
    commands:
    - npm install

  test:lint:ng:
    group: lint
    image: node:10-alpine
    commands:
    - npm run lint:ng

  test:lint:html:
    group: lint
    image: node:10-alpine
    commands:
    - npm run lint:html

  test:spec:
    image: weboaks/node-karma-protractor-chrome:alpine-root
    commands:
    - npm run test:ci

  test:e2e:
    image: weboaks/node-karma-protractor-chrome:alpine-root
    commands:
    - npm run e2e

  build:
    image: node:10-alpine
    commands:
    - npm run build:prod

notify:mail:
  image: drillster/drone-email
  from: ci@mattagohni.de
  host: sslout.df.eu
  when:
    event: push
    status: [changed, failure]
  secrets:
  - source: ci_email_user
    target: plugin_username
  - source: ci_email_password
    target: plugin_password

services:
  chrome:
    # @TODO Have a look at https://gitlab.com/DMore/chrome-mink-driver
    image: selenium/standalone-chrome
