image: trion/ng-cli-karma

cache:
  paths:
  - node_modules/

test:
  script:
  - rm ./package-lock.json
  - npm install
  - ./node_modules/@angular/cli/bin/ng test --progress false --watch=false
  - ./node_modules/@angular/cli/bin/ng e2e --progress false --config protractor.ci.conf.js --webdriver-update false
  - ./node_modules/@angular/cli/bin/ng build --progress false --prod
