image: trion/ng-cli-karma

cache:
  paths:
  - node_modules/

test:
  script:
  - rm ./package-lock.json
  - npm install
  - ./node_modules/@angular/cli/bin/ng test --progress false --watch=false
  - ./node_modules/@angular/cli/bin/ng e2e --progress false --watch=false
  - ./node_modules/@angular/cli/bin/ng build --progress false --prod --base-href XXX-stage.surge.sh
  - ./node_modules/.bin/surge -p dist/ --domain XXX-stage.surge.sh
